# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'desafio_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for desafio_ios
  pod 'Alamofire', '~> 5.0.0-rc.2'
  target 'desafio_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'desafio_iosUITests' do
    # Pods for testing
  end

end
